In [59]:
import numpy as np 
x= np.array([[1,3.2,2],
   [1,3.6,5],
   [1,2.8,3],
   [1,2.4,4]])
xt = np.transpose(x)

In [60]:
xx = np.matmul(xt,x)
xx

array([[ 4. , 12. , 14. ],
       [12. , 36.8, 42.4],
       [14. , 42.4, 54. ]])

In [67]:
y= np.array([[40,46,38,39]])

xy =np.matmul(xt,y.reshape(4,1))

In [68]:
xy

array([[163. ],
       [493.6],
       [580. ]])

In [75]:
np.matmul(np.linalg.inv(xx),xy)

array([[20.5],
       [ 5. ],
       [ 1.5]])

In [48]:
xx

array([[15.24, 22.52, 15.96, 16.68],
       [22.52, 38.96, 26.08, 29.64],
       [15.96, 26.08, 17.84, 19.72],
       [16.68, 29.64, 19.72, 22.76]])

In [71]:
print(x.shape,xt.shape,y.shape,xx.shape,xy.shape,np.linalg.inv(xx).shape)

(4, 3) (3, 4) (1, 4) (3, 3) (3, 1) (3, 3)
